id: PA99E9349
initial_creation_type: ocr
source_metadata:
  volumes:
    979dab76f8f34e4aba89a04ac25260d7:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: ཁྲོ་བོའི་རྒྱལ་པོ་འཕགས་པ་མི་གཡོ་བ་ལ་བསྟོད་པ།
      total_pages: 1044
      volume_number: 38
